# Generated by Django 5.2.16 on 2026-07-25 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['institution', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College')], max_length=10)),
                ('cycle_length', models.PositiveSmallIntegerField(default=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=32)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_divisions', to='core.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_divisions', to='core.institution')),
            ],
            options={
                'ordering': ['institution', 'name', 'section'],
            },
        ),
        migrations.CreateModel(
            name='ElectiveGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_groups', to='core.academicterm')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_groups', to='core.institution')),
            ],
            options={
                'ordering': ['institution', 'term', 'name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.institution'),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_terms', to='core.institution'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32)),
                ('is_elective', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.institution')),
            ],
            options={
                'ordering': ['institution', 'department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('max_periods_per_day', models.PositiveSmallIntegerField()),
                ('max_periods_per_week', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.institution')),
            ],
            options={
                'ordering': ['institution', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.PositiveSmallIntegerField()),
                ('is_lab', models.BooleanField(default=False)),
                ('block_size', models.PositiveSmallIntegerField(default=1)),
                ('class_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requirements', to='core.classdivision')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requirements', to='core.academicterm')),
                ('elective_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_requirements', to='core.electivegroup')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requirements', to='core.institution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requirements', to='core.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_requirements', to='core.teacher')),
            ],
            options={
                'ordering': ['institution', 'term', 'class_division', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_identifier', models.PositiveSmallIntegerField()),
                ('period_number', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.institution')),
            ],
            options={
                'ordering': ['institution', 'day_identifier', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='FacultyDutyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(choices=[('PAPER_VALUATION', 'Paper Valuation'), ('INVIGILATION', 'Invigilation'), ('NAAC_COMPLIANCE', 'NAAC Compliance'), ('RESEARCH', 'Research'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_duty_blocks', to='core.academicterm')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_duty_blocks', to='core.institution')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_duty_blocks', to='core.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_blocks', to='core.timeslot')),
            ],
            options={
                'ordering': ['institution', 'term', 'teacher', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='TimetableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('class_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_cells', to='core.classdivision')),
                ('course_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_cells', to='core.courserequirement')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_cells', to='core.institution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_cells', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_cells', to='core.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_cells', to='core.academicterm')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_cells', to='core.timeslot')),
            ],
            options={
                'ordering': ['institution', 'term', 'class_division', 'time_slot'],
            },
        ),
        migrations.AddIndex(
            model_name='electivegroup',
            index=models.Index(fields=['institution', 'term'], name='core_electi_institu_f24cd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='electivegroup',
            unique_together={('term', 'name')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['institution', 'name'], name='core_depart_institu_8c8256_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('institution', 'name')},
        ),
        migrations.AddIndex(
            model_name='classdivision',
            index=models.Index(fields=['institution', 'department'], name='core_classd_institu_42f6ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classdivision',
            unique_together={('institution', 'department', 'name', 'section')},
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['institution', 'is_active'], name='core_academ_institu_5d248b_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='term_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('institution', 'name')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['institution', 'department'], name='core_subjec_institu_571f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['institution', 'is_elective'], name='core_subjec_institu_adecdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('institution', 'code')},
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['institution', 'is_active'], name='core_teache_institu_53ecc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('max_periods_per_day__gt', 0), ('max_periods_per_week__gt', 0)), name='teacher_caps_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('institution', 'email')},
        ),
        migrations.AddIndex(
            model_name='courserequirement',
            index=models.Index(fields=['institution', 'term'], name='core_course_institu_b38b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='courserequirement',
            index=models.Index(fields=['elective_group'], name='core_course_electiv_f82197_idx'),
        ),
        migrations.AddConstraint(
            model_name='courserequirement',
            constraint=models.CheckConstraint(condition=models.Q(('periods_per_week__gt', 0)), name='coursereq_periods_positive'),
        ),
        migrations.AddConstraint(
            model_name='courserequirement',
            constraint=models.CheckConstraint(condition=models.Q(('block_size__gt', 0)), name='coursereq_block_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='courserequirement',
            constraint=models.CheckConstraint(condition=models.Q(('block_size__lte', models.F('periods_per_week'))), name='coursereq_block_not_exceed_weekly'),
        ),
        migrations.AlterUniqueTogether(
            name='courserequirement',
            unique_together={('term', 'class_division', 'subject')},
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['institution', 'day_identifier'], name='core_timesl_institu_188b84_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='timeslot_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('institution', 'day_identifier', 'period_number')},
        ),
        migrations.AddIndex(
            model_name='facultydutyblock',
            index=models.Index(fields=['institution', 'term', 'teacher'], name='core_facult_institu_3ffb51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facultydutyblock',
            unique_together={('term', 'teacher', 'time_slot')},
        ),
        migrations.AddIndex(
            model_name='timetablecell',
            index=models.Index(fields=['institution', 'term'], name='core_timeta_institu_968abc_idx'),
        ),
        migrations.AddIndex(
            model_name='timetablecell',
            index=models.Index(fields=['term', 'class_division'], name='core_timeta_term_id_051e80_idx'),
        ),
        migrations.AddIndex(
            model_name='timetablecell',
            index=models.Index(fields=['term', 'teacher'], name='core_timeta_term_id_845e7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetablecell',
            unique_together={('term', 'class_division', 'time_slot'), ('term', 'teacher', 'time_slot')},
        ),
    ]
