# Generated by Django 5.2.16 on 2026-07-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeGridConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_day', models.PositiveSmallIntegerField()),
                ('period_duration_minutes', models.PositiveSmallIntegerField()),
                ('day_start_time', models.TimeField()),
                ('breaks', models.JSONField(blank=True, default=list)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_grid_config', to='core.institution')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('periods_per_day__gt', 0)), name='timegridconfig_periods_positive'), models.CheckConstraint(condition=models.Q(('period_duration_minutes__gt', 0)), name='timegridconfig_duration_positive')],
            },
        ),
    ]
