# Generated by Django 5.2.16 on 2026-07-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_solverrun_objective_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_identifier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_days', to='core.institution')),
            ],
            options={
                'ordering': ['institution', 'date'],
                'indexes': [models.Index(fields=['institution', 'date'], name='core_academ_institu_caa93e_idx'), models.Index(fields=['institution', 'day_identifier'], name='core_academ_institu_bf74d6_idx')],
                'unique_together': {('institution', 'date')},
            },
        ),
    ]
