# Generated by Django 5.2.16 on 2026-07-25 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timegridconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetablecell',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetablecell',
            name='elective_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_cells', to='core.electivegroup'),
        ),
        migrations.AddConstraint(
            model_name='timetablecell',
            constraint=models.UniqueConstraint(condition=models.Q(('elective_group__isnull', True)), fields=('term', 'class_division', 'time_slot'), name='timetablecell_unique_class_slot_non_elective'),
        ),
        migrations.AddConstraint(
            model_name='timetablecell',
            constraint=models.UniqueConstraint(condition=models.Q(('elective_group__isnull', False)), fields=('term', 'class_division', 'time_slot', 'subject'), name='timetablecell_unique_class_slot_subject_elective'),
        ),
        migrations.AddConstraint(
            model_name='timetablecell',
            constraint=models.UniqueConstraint(fields=('term', 'teacher', 'time_slot'), name='timetablecell_unique_teacher_slot'),
        ),
    ]
