# Generated by Django 5.2.16 on 2026-07-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_timetablecell_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolverRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['institution', 'teacher', 'subject'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='timetablecell',
            name='timetablecell_unique_class_slot_non_elective',
        ),
        migrations.RemoveConstraint(
            model_name='timetablecell',
            name='timetablecell_unique_class_slot_subject_elective',
        ),
        migrations.AddConstraint(
            model_name='timetablecell',
            constraint=models.UniqueConstraint(condition=models.Q(('elective_group__isnull', True)), fields=('term', 'class_division', 'time_slot'), name='no_double_booking_non_elective'),
        ),
        migrations.AddConstraint(
            model_name='timetablecell',
            constraint=models.UniqueConstraint(fields=('term', 'class_division', 'time_slot', 'subject'), name='no_duplicate_subject_cell'),
        ),
        migrations.AddField(
            model_name='solverrun',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solver_runs', to='core.institution'),
        ),
        migrations.AddField(
            model_name='solverrun',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solver_runs', to='core.academicterm'),
        ),
        migrations.AddField(
            model_name='teachersubjecteligibility',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_eligibilities', to='core.institution'),
        ),
        migrations.AddField(
            model_name='teachersubjecteligibility',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_teachers', to='core.subject'),
        ),
        migrations.AddField(
            model_name='teachersubjecteligibility',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_eligibilities', to='core.teacher'),
        ),
        migrations.AddIndex(
            model_name='solverrun',
            index=models.Index(fields=['institution', 'term'], name='core_solver_institu_1908cb_idx'),
        ),
        migrations.AddIndex(
            model_name='solverrun',
            index=models.Index(fields=['status'], name='core_solver_status_656e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjecteligibility',
            index=models.Index(fields=['institution', 'teacher'], name='core_teache_institu_b67188_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjecteligibility',
            index=models.Index(fields=['institution', 'subject'], name='core_teache_institu_94fb89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjecteligibility',
            unique_together={('teacher', 'subject')},
        ),
    ]
