# Generated by Django 5.2.16 on 2026-07-25 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solverrun_teachersubjecteligibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solverrun',
            name='objective_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='cognitive_load_priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10),
        ),
        migrations.CreateModel(
            name='SolverWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_weight', models.PositiveSmallIntegerField(default=50)),
                ('cognitive_load_weight', models.PositiveSmallIntegerField(default=50)),
                ('fair_rotation_weight', models.PositiveSmallIntegerField(default=50)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solver_weight_config', to='core.institution')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('gap_weight__gte', 0), ('gap_weight__lte', 100), ('cognitive_load_weight__gte', 0), ('cognitive_load_weight__lte', 100), ('fair_rotation_weight__gte', 0), ('fair_rotation_weight__lte', 100)), name='solverweightconfig_weights_in_range')],
            },
        ),
    ]
