# Generated by Django 5.2.16 on 2026-07-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_academiccalendarday'),
    ]

    operations = [
        migrations.AddField(
            model_name='solverrun',
            name='trigger',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('RESIGNATION_RECOVERY', 'Resignation Recovery')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='timetablecell',
            name='locked_reason',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('RESIGNATION_RECOVERY', 'Resignation Recovery')], max_length=20, null=True),
        ),
    ]
