# Generated by Django 5.2.16 on 2026-08-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='core.institution')),
                ('original_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='core.timetablecell')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_assignments', to='core.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='core.academicterm')),
            ],
            options={
                'ordering': ['-date', 'institution'],
                'indexes': [models.Index(fields=['institution', 'date'], name='core_substi_institu_faa01b_idx'), models.Index(fields=['substitute_teacher', 'date'], name='core_substi_substit_2f0dbe_idx')],
                'unique_together': {('original_cell', 'date')},
            },
        ),
    ]
